package pl.pjait;

public enum Ability {
    DARK_VISION,
    SUPER_ABILITY,
    SUPER_STAMINA,
    FLYING,
    INJURY_PRONE,
    HAND_TO_HAND_COMBAT,
    SWORD_FIGHTING,
    AXE_FIGHTING,
    SPEAR_FIGHTING,
    MAGIC,
    ALCHEMIST,
    SNEAKING,
    POISONING,
    INVENTORY_REPAIRING,
    SHOOTING
}
